// <auto-generated />
using System;
using CarWatchBelgium.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarWatchBelgium.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("BE");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EUR");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("FallbackHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastPriceChangeAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Make")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MileageKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PowerHp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenAtUtc");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("MileageKm");

                    b.HasIndex("Price");

                    b.HasIndex("Year");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL AND [ExternalId] <> ''");

                    b.HasIndex("Source", "FallbackHash")
                        .IsUnique();

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EUR");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "CapturedAtUtc");

                    b.ToTable("PriceHistories", (string)null);
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("BE");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ExcludedKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastMatchedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Make")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxMileageKm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinPowerHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriceMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PriceMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadiusKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("SavedSearches", (string)null);
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.SavedSearchMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("SavedSearchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("MatchedAtUtc");

                    b.HasIndex("SavedSearchId", "ListingId")
                        .IsUnique();

                    b.ToTable("SavedSearchMatches", (string)null);
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.UserListingState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("FavoritedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SeenAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("IsIgnored");

                    b.HasIndex("IsSeen");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId", "ListingId")
                        .IsUnique();

                    b.ToTable("UserListingStates", (string)null);
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("CarWatchBelgium.Domain.Entities.Listing", "Listing")
                        .WithMany("PriceHistory")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.SavedSearch", b =>
                {
                    b.HasOne("CarWatchBelgium.Domain.Entities.User", "User")
                        .WithMany("SavedSearches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.SavedSearchMatch", b =>
                {
                    b.HasOne("CarWatchBelgium.Domain.Entities.Listing", "Listing")
                        .WithMany("SavedSearchMatches")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarWatchBelgium.Domain.Entities.SavedSearch", "SavedSearch")
                        .WithMany("Matches")
                        .HasForeignKey("SavedSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("SavedSearch");
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.UserListingState", b =>
                {
                    b.HasOne("CarWatchBelgium.Domain.Entities.Listing", "Listing")
                        .WithMany("UserStates")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarWatchBelgium.Domain.Entities.User", "User")
                        .WithMany("ListingStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.Listing", b =>
                {
                    b.Navigation("PriceHistory");

                    b.Navigation("SavedSearchMatches");

                    b.Navigation("UserStates");
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.SavedSearch", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("CarWatchBelgium.Domain.Entities.User", b =>
                {
                    b.Navigation("ListingStates");

                    b.Navigation("SavedSearches");
                });
#pragma warning restore 612, 618
        }
    }
}
